spring:
  datasource:
    username: root
    password: Pan19970218
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-2ze806i1i971v3wycoo.mysql.rds.aliyuncs.com:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  cloud:
    nacos:
      discovery:
        server-addr: 47.95.216.30:8848
    alicloud:
      access-key: LTAI5tSbzmwfVQsoJUjH9NbK
      secret-key: GYNIZhsUolshOdHUfflSdlv8XWHjWB
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/
  redis:
    host: 47.95.216.30
    port: 6379

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 11000
logging:
  level:
    com.pandy.gulimall.*: debug

